site_name: RSECon25 Workshop- Deploying a Web Application with Kubernetes
nav:
- index.md
- why-kubernetes.md
- kubernetes-architecture.md
- kubernetes-dashboard.md
- kubechaos.md
theme: 
  name: mkdocs
  palette:
    primary: teal
    accent: indigo
  logo: assets/CN-SIG-logo.png
  features: 
    - instant
  
repo_url: https://github.com/rosalindfranklininstitute/rsecon25-intro-to-kubernetes
edit_uri: tree/main/tutorial


