site_name: RSECon25 Workshop- Deploying a Web Application with Kubernetes
nav:
- index.md
- Pre-reading:
  - why-kubernetes.md
  - kubernetes-architecture.md
- Lessons:
  - lesson0-kubernetes-dashboard.md
  - lesson1-kubechaos.md
  - lesson2-kubechaos-update.md
  - Lessons 2 extension task:
    - Multiple Deployments: lesson2-kubechaos-extra.md
  - lesson3-config-maps.md
  - lesson4-helm.md
theme: 
  name: material
  palette:
    primary: teal
    accent: indigo
  logo: assets/CN-SIG-logo.png
  features: 
    - instant
  
repo_url: https://github.com/rosalindfranklininstitute/rsecon25-intro-to-kubernetes
edit_uri: tree/main/tutorial


